/**
 * Training data for the Facebook Bot AI Intent Classifier
 * Supports both Bengali (à¦¬à¦¾à¦‚à¦²à¦¾) and English messages
 */

export type Intent =
    | "FIND_BLOOD"
    | "REGISTER_DONOR"
    | "UPDATE_DONATION"
    | "REQUEST_BLOOD"
    | "BLOOD_INFO"
    | "GREET"
    | "HELP"
    | "THANK_YOU"
    | "UNKNOWN";

export interface TrainingSample {
    text: string;
    intent: Intent;
}

export const trainingData: TrainingSample[] = [
    // â”€â”€â”€ FIND_BLOOD â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    { text: "I need blood",                                                       intent: "FIND_BLOOD" },
    { text: "need blood urgently",                                                intent: "FIND_BLOOD" },
    { text: "find blood donor",                                                   intent: "FIND_BLOOD" },
    { text: "find a donor",                                                       intent: "FIND_BLOOD" },
    { text: "looking for blood donor",                                            intent: "FIND_BLOOD" },
    { text: "search blood donor",                                                 intent: "FIND_BLOOD" },
    { text: "need A positive blood",                                              intent: "FIND_BLOOD" },
    { text: "need B negative blood",                                              intent: "FIND_BLOOD" },
    { text: "need O positive blood",                                              intent: "FIND_BLOOD" },
    { text: "need AB positive blood",                                             intent: "FIND_BLOOD" },
    { text: "blood needed",                                                       intent: "FIND_BLOOD" },
    { text: "blood required",                                                     intent: "FIND_BLOOD" },
    { text: "blood emergency",                                                    intent: "FIND_BLOOD" },
    { text: "urgent blood needed",                                                intent: "FIND_BLOOD" },
    { text: "donor needed",                                                       intent: "FIND_BLOOD" },
    { text: "blood donor near me",                                                intent: "FIND_BLOOD" },
    { text: "where can I find blood donor",                                       intent: "FIND_BLOOD" },
    { text: "patient needs blood",                                                intent: "FIND_BLOOD" },
    { text: "hospital needs blood",                                               intent: "FIND_BLOOD" },
    { text: "A+ blood needed",                                                    intent: "FIND_BLOOD" },
    { text: "B+ donor near dhaka",                                                intent: "FIND_BLOOD" },
    { text: "O- blood required urgently",                                         intent: "FIND_BLOOD" },
    { text: "AB+ blood",                                                          intent: "FIND_BLOOD" },
    { text: "need donor in chittagong",                                           intent: "FIND_BLOOD" },
    { text: "find blood in sylhet",                                               intent: "FIND_BLOOD" },
    { text: "blood donor dhaka",                                                  intent: "FIND_BLOOD" },
    { text: "can someone donate blood",                                           intent: "FIND_BLOOD" },
    { text: "2 bags of A+ blood needed tomorrow",                                 intent: "FIND_BLOOD" },
    { text: "need 2 units of blood in hospital",                                  intent: "FIND_BLOOD" },
    { text: "donor list in rangpur city",                                         intent: "FIND_BLOOD" },
    { text: "give me a list of B+ donors",                                        intent: "FIND_BLOOD" },
    { text: "need O- blood at Dhaka Medical",                                     intent: "FIND_BLOOD" },
    { text: "rare blood group AB negative needed",                                intent: "FIND_BLOOD" },
    { text: "where to find rare blood group",                                     intent: "FIND_BLOOD" },
    { text: "emergency A negative blood needed now",                              intent: "FIND_BLOOD" },
    { text: "operation theater needs blood",                                      intent: "FIND_BLOOD" },
    { text: "my father needs blood transfusion",                                  intent: "FIND_BLOOD" },
    { text: "surgery tomorrow need blood ready",                                  intent: "FIND_BLOOD" },
    { text: "accident victim needs O+ blood",                                     intent: "FIND_BLOOD" },
    { text: "ICU patient needs blood",                                            intent: "FIND_BLOOD" },
    // Bengali â€“ à¦¸à¦°à¦¾à¦¸à¦°à¦¿ à¦…à¦¨à§à¦°à§‹à¦§
    { text: "à¦°à¦•à§à¦¤ à¦¦à¦°à¦•à¦¾à¦°",                                                         intent: "FIND_BLOOD" },
    { text: "à¦°à¦•à§à¦¤ à¦šà¦¾à¦‡",                                                           intent: "FIND_BLOOD" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦¦à¦°à¦•à¦¾à¦°",                                                     intent: "FIND_BLOOD" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦–à§à¦à¦œà¦›à¦¿",                                                   intent: "FIND_BLOOD" },
    { text: "à¦•à¦¾à¦›à¦¾à¦•à¦¾à¦›à¦¿ à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦–à§à¦à¦œà§à¦¨",                                          intent: "FIND_BLOOD" },
    { text: "à¦ à¦ªà¦œà¦¿à¦Ÿà¦¿à¦­ à¦°à¦•à§à¦¤ à¦šà¦¾à¦‡",                                                  intent: "FIND_BLOOD" },
    { text: "à¦¬à¦¿ à¦ªà¦œà¦¿à¦Ÿà¦¿à¦­ à¦°à¦•à§à¦¤ à¦¦à¦°à¦•à¦¾à¦°",                                               intent: "FIND_BLOOD" },
    { text: "à¦“ à¦ªà¦œà¦¿à¦Ÿà¦¿à¦­ à¦°à¦•à§à¦¤ à¦šà¦¾à¦‡",                                                  intent: "FIND_BLOOD" },
    { text: "à¦à¦¬à¦¿ à¦ªà¦œà¦¿à¦Ÿà¦¿à¦­ à¦°à¦•à§à¦¤ à¦¦à¦°à¦•à¦¾à¦°",                                              intent: "FIND_BLOOD" },
    { text: "à¦œà¦°à§à¦°à¦¿ à¦°à¦•à§à¦¤ à¦¦à¦°à¦•à¦¾à¦°",                                                   intent: "FIND_BLOOD" },
    { text: "à¦°à¦•à§à¦¤ à¦–à§à¦à¦œà¦›à¦¿",                                                        intent: "FIND_BLOOD" },
    { text: "à¦†à¦®à¦¾à¦° à¦°à¦•à§à¦¤ à¦¦à¦°à¦•à¦¾à¦°",                                                    intent: "FIND_BLOOD" },
    { text: "à¦°à§‹à¦—à§€à¦° à¦°à¦•à§à¦¤ à¦²à¦¾à¦—à¦¬à§‡",                                                   intent: "FIND_BLOOD" },
    { text: "à¦¹à¦¾à¦¸à¦ªà¦¾à¦¤à¦¾à¦²à§‡ à¦°à¦•à§à¦¤ à¦²à¦¾à¦—à¦¬à§‡",                                               intent: "FIND_BLOOD" },
    { text: "A+ à¦°à¦•à§à¦¤ à¦¦à¦°à¦•à¦¾à¦°",                                                      intent: "FIND_BLOOD" },
    { text: "B+ à¦°à¦•à§à¦¤ à¦šà¦¾à¦‡",                                                        intent: "FIND_BLOOD" },
    { text: "O- à¦°à¦•à§à¦¤ à¦œà¦°à§à¦°à¦¿",                                                      intent: "FIND_BLOOD" },
    { text: "AB+ à¦°à¦•à§à¦¤ à¦²à¦¾à¦—à¦¬à§‡",                                                     intent: "FIND_BLOOD" },
    { text: "à¦¢à¦¾à¦•à¦¾à¦¯à¦¼ à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦¦à¦°à¦•à¦¾à¦°",                                              intent: "FIND_BLOOD" },
    { text: "à¦šà¦Ÿà§à¦Ÿà¦—à§à¦°à¦¾à¦®à§‡ à¦°à¦•à§à¦¤ à¦šà¦¾à¦‡",                                                intent: "FIND_BLOOD" },
    { text: "à¦¸à¦¿à¦²à§‡à¦Ÿà§‡ à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦–à§à¦à¦œà¦›à¦¿",                                            intent: "FIND_BLOOD" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨ à¦•à¦°à¦¤à§‡ à¦¯à§‹à¦—à¦¾à¦¯à§‹à¦— à¦•à¦°à§à¦¨",                                          intent: "FIND_BLOOD" },
    { text: "à¦°à¦•à§à¦¤ à¦¦à§‡à¦¬à§‡ à¦•à§‡",                                                       intent: "FIND_BLOOD" },
    { text: "à¦°à¦•à§à¦¤à§‡à¦° à¦ªà§à¦°à¦¯à¦¼à§‹à¦œà¦¨",                                                    intent: "FIND_BLOOD" },
    { text: "à¦¡à§‹à¦¨à¦¾à¦° à¦–à§à¦à¦œà¦›à¦¿",                                                       intent: "FIND_BLOOD" },
    { text: "à¦¡à§‹à¦¨à¦¾à¦° à¦¦à¦°à¦•à¦¾à¦°",                                                        intent: "FIND_BLOOD" },
    { text: "à¦œà¦°à§à¦°à¦¿ O+ à¦°à¦•à§à¦¤ à¦ªà§à¦°à¦¯à¦¼à§‹à¦œà¦¨ à¦¢à¦¾à¦•à¦¾ à¦®à§‡à¦¡à¦¿à¦•à§‡à¦² à¦•à¦²à§‡à¦œà§‡à¦° à¦†à¦¶à§‡à¦ªà¦¾à¦¶à§‡ à¦¡à§‹à¦¨à¦¾à¦° à¦†à¦›à§‡",   intent: "FIND_BLOOD" },
    { text: "à¦šà¦Ÿà§à¦Ÿà¦—à§à¦°à¦¾à¦® à¦®à¦¾ à¦“ à¦¶à¦¿à¦¶à§ à¦¹à¦¾à¦¸à¦ªà¦¾à¦¤à¦¾à¦²à§‡ à§¨ à¦¬à§à¦¯à¦¾à¦— A- à¦°à¦•à§à¦¤ à¦²à¦¾à¦—à¦¬à§‡",             intent: "FIND_BLOOD" },
    { text: "à¦°à¦‚à¦ªà§à¦° à¦¸à¦¿à¦Ÿà¦¿ à¦à¦°à¦¿à¦¯à¦¼à¦¾à¦¯à¦¼ B+ à¦¡à§‹à¦¨à¦¾à¦°à¦¦à§‡à¦° à¦²à¦¿à¦¸à§à¦Ÿ à¦¦à¦¾à¦“",                         intent: "FIND_BLOOD" },
    { text: "à¦¢à¦¾à¦•à¦¾ à¦®à§‡à¦¡à¦¿à¦•à§‡à¦²à§‡ O à¦ªà¦œà¦¿à¦Ÿà¦¿à¦­ à¦°à¦•à§à¦¤ à¦²à¦¾à¦—à¦¬à§‡ à¦•à¦¾à¦² à¦¸à¦•à¦¾à¦²à§‡",                     intent: "FIND_BLOOD" },
    { text: "à§¨ à¦¬à§à¦¯à¦¾à¦— à¦°à¦•à§à¦¤ à¦¦à¦°à¦•à¦¾à¦°",                                                  intent: "FIND_BLOOD" },
    { text: "à¦°à§‡à¦¯à¦¼à¦¾à¦° à¦¬à§à¦²à¦¾à¦¡ à¦—à§à¦°à§à¦ª AB- à¦•à§‹à¦¥à¦¾à¦¯à¦¼ à¦ªà¦¾à¦“à¦¯à¦¼à¦¾ à¦¯à¦¾à¦¬à§‡",                          intent: "FIND_BLOOD" },
    { text: "à¦¬à¦¿à¦°à¦² à¦°à¦•à§à¦¤à§‡à¦° à¦—à§à¦°à§à¦ª à¦•à§‹à¦¥à¦¾à¦¯à¦¼ à¦ªà¦¾à¦¬à§‹",                                      intent: "FIND_BLOOD" },
    { text: "AB à¦¨à§‡à¦—à§‡à¦Ÿà¦¿à¦­ à¦°à¦•à§à¦¤ à¦œà¦°à§à¦°à¦¿",                                              intent: "FIND_BLOOD" },
    { text: "à¦¥à§à¦¯à¦¾à¦²à¦¾à¦¸à§‡à¦®à¦¿à¦¯à¦¼à¦¾ à¦°à§‹à¦—à§€à¦° à¦œà¦¨à§à¦¯ à¦¨à¦¿à¦¯à¦¼à¦®à¦¿à¦¤ à¦°à¦•à§à¦¤ à¦²à¦¾à¦—à¦¬à§‡",                       intent: "FIND_BLOOD" },
    { text: "à¦¡à§‹à¦¨à¦¾à¦°à¦¦à§‡à¦° à¦à¦•à¦Ÿà¦¾ à¦²à¦¿à¦¸à§à¦Ÿ à¦¦à¦¿à¦¨",                                            intent: "FIND_BLOOD" },
    { text: "à¦•à¦¾à¦›à§‡à¦° à¦¡à§‹à¦¨à¦¾à¦° à¦•à¦¾à¦°à¦¾ à¦†à¦›à§‡",                                               intent: "FIND_BLOOD" },
    { text: "à¦…à¦ªà¦¾à¦°à§‡à¦¶à¦¨à§‡à¦° à¦œà¦¨à§à¦¯ à¦°à¦•à§à¦¤ à¦²à¦¾à¦—à¦¬à§‡",                                          intent: "FIND_BLOOD" },
    { text: "à¦†à¦‡à¦¸à¦¿à¦‡à¦‰à¦¤à§‡ à¦°à§‹à¦—à§€ à¦°à¦•à§à¦¤ à¦¦à¦°à¦•à¦¾à¦°",                                          intent: "FIND_BLOOD" },
    { text: "à¦¦à§à¦°à§à¦˜à¦Ÿà¦¨à¦¾à¦¯à¦¼ à¦†à¦¹à¦¤ à¦°à¦•à§à¦¤ à¦²à¦¾à¦—à¦¬à§‡",                                           intent: "FIND_BLOOD" },
    { text: "à¦•à§à¦®à¦¿à¦²à§à¦²à¦¾à¦¯à¦¼ O+ à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦ªà¦¾à¦¬à§‹ à¦•à§‹à¦¥à¦¾à¦¯à¦¼",                                 intent: "FIND_BLOOD" },
    { text: "à¦®à¦¯à¦¼à¦®à¦¨à¦¸à¦¿à¦‚à¦¹à§‡ A à¦¨à§‡à¦—à§‡à¦Ÿà¦¿à¦­ à¦°à¦•à§à¦¤ à¦šà¦¾à¦‡",                                      intent: "FIND_BLOOD" },
    { text: "à¦°à¦¾à¦œà¦¶à¦¾à¦¹à§€à¦¤à§‡ AB+ à¦¡à§‹à¦¨à¦¾à¦° à¦¦à¦°à¦•à¦¾à¦°",                                          intent: "FIND_BLOOD" },
    { text: "à¦–à§à¦²à¦¨à¦¾à¦¯à¦¼ B à¦¨à§‡à¦—à§‡à¦Ÿà¦¿à¦­ à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦•à§‹à¦¥à¦¾à¦¯à¦¼ à¦ªà¦¾à¦¬à§‹",                             intent: "FIND_BLOOD" },
    { text: "à¦¬à¦°à¦¿à¦¶à¦¾à¦²à§‡ à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦¦à¦°à¦•à¦¾à¦°",                                              intent: "FIND_BLOOD" },
    { text: "à¦¡à§‹à¦¨à¦¾à¦° à¦²à¦¿à¦¸à§à¦Ÿ à¦¦à§‡à¦–à¦¤à§‡ à¦šà¦¾à¦‡",                                              intent: "FIND_BLOOD" },
    { text: "à¦†à¦®à¦¾à¦° à¦•à¦¾à¦›à§‡à¦° à¦à¦²à¦¾à¦•à¦¾à¦¯à¦¼ à¦¡à§‹à¦¨à¦¾à¦° à¦†à¦›à§‡",                                        intent: "FIND_BLOOD" },

    // â”€â”€â”€ REGISTER_DONOR â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    { text: "I want to donate blood",                                             intent: "REGISTER_DONOR" },
    { text: "register as donor",                                                  intent: "REGISTER_DONOR" },
    { text: "become a blood donor",                                               intent: "REGISTER_DONOR" },
    { text: "sign up as donor",                                                   intent: "REGISTER_DONOR" },
    { text: "I want to register",                                                 intent: "REGISTER_DONOR" },
    { text: "add me as donor",                                                    intent: "REGISTER_DONOR" },
    { text: "I can donate blood",                                                 intent: "REGISTER_DONOR" },
    { text: "how to register as donor",                                           intent: "REGISTER_DONOR" },
    { text: "register",                                                           intent: "REGISTER_DONOR" },
    { text: "want to be donor",                                                   intent: "REGISTER_DONOR" },
    { text: "I am willing to donate",                                             intent: "REGISTER_DONOR" },
    { text: "put me on donor list",                                               intent: "REGISTER_DONOR" },
    { text: "add my name to donors",                                              intent: "REGISTER_DONOR" },
    { text: "create donor profile",                                               intent: "REGISTER_DONOR" },
    { text: "join as blood donor",                                                intent: "REGISTER_DONOR" },
    // Bengali
    { text: "à¦†à¦®à¦¿ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¤à§‡ à¦šà¦¾à¦‡",                                                 intent: "REGISTER_DONOR" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦¹à¦¿à¦¸à§‡à¦¬à§‡ à¦¨à¦¿à¦¬à¦¨à§à¦§à¦¨ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                 intent: "REGISTER_DONOR" },
    { text: "à¦¨à¦¿à¦¬à¦¨à§à¦§à¦¨ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                                  intent: "REGISTER_DONOR" },
    { text: "à¦¡à§‹à¦¨à¦¾à¦° à¦¹à¦¤à§‡ à¦šà¦¾à¦‡",                                                     intent: "REGISTER_DONOR" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                                  intent: "REGISTER_DONOR" },
    { text: "à¦†à¦®à¦¾à¦•à§‡ à¦¡à§‹à¦¨à¦¾à¦° à¦¹à¦¿à¦¸à§‡à¦¬à§‡ à¦¯à§‹à¦— à¦•à¦°à§à¦¨",                                       intent: "REGISTER_DONOR" },
    { text: "à¦°à§‡à¦œà¦¿à¦¸à§à¦Ÿà§à¦°à§‡à¦¶à¦¨ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                              intent: "REGISTER_DONOR" },
    { text: "à¦†à¦®à¦¿ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¤à§‡ à¦ªà¦¾à¦°à¦¬",                                                 intent: "REGISTER_DONOR" },
    { text: "à¦°à§‡à¦œà¦¿à¦¸à§à¦Ÿà¦¾à¦°",                                                          intent: "REGISTER_DONOR" },
    { text: "à¦¡à§‹à¦¨à¦¾à¦° à¦¤à¦¾à¦²à¦¿à¦•à¦¾à¦¯à¦¼ à¦¯à§‹à¦— à¦¦à¦¿à¦¤à§‡ à¦šà¦¾à¦‡",                                        intent: "REGISTER_DONOR" },
    { text: "à¦¡à§‹à¦¨à¦¾à¦° à¦¹à¦¿à¦¸à§‡à¦¬à§‡ à¦¨à¦¾à¦® à¦²à§‡à¦–à¦¾à¦¤à§‡ à¦šà¦¾à¦‡ à¦•à§€ à¦•à¦°à¦¤à§‡ à¦¹à¦¬à§‡",                           intent: "REGISTER_DONOR" },
    { text: "à¦†à¦®à¦¾à¦° à¦ªà§à¦°à§‹à¦«à¦¾à¦‡à¦² à¦…à§à¦¯à¦¾à¦­à§‡à¦‡à¦²à§‡à¦¬à¦² à¦¨à¦¾ à¦•à¦°à§‹",                                  intent: "REGISTER_DONOR" },
    { text: "à¦†à¦®à¦¿ à¦à¦–à¦¨ à¦…à¦¸à§à¦¸à§à¦¥ à¦ªà§à¦°à§‹à¦«à¦¾à¦‡à¦² à¦¬à¦¨à§à¦§ à¦•à¦°à§‹",                                  intent: "REGISTER_DONOR" },
    { text: "profile unavailable mark",                                           intent: "REGISTER_DONOR" },
    { text: "à¦¨à¦¿à¦¬à¦¨à§à¦§à¦¨",                                                             intent: "REGISTER_DONOR" },
    { text: "à¦¡à§‹à¦¨à¦¾à¦° à¦¹à¦¿à¦¸à§‡à¦¬à§‡ à¦¨à¦¾à¦® à¦¦à¦¿à¦¤à§‡ à¦šà¦¾à¦‡",                                          intent: "REGISTER_DONOR" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡ à¦†à¦—à§à¦°à¦¹à§€",                                                     intent: "REGISTER_DONOR" },
    { text: "à¦†à¦®à¦¿ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¤à§‡ à¦ªà§à¦°à¦¸à§à¦¤à§à¦¤",                                              intent: "REGISTER_DONOR" },
    { text: "à¦¬à§à¦²à¦¾à¦¡ à¦¡à§‹à¦¨à¦¾à¦° à¦¹à¦¤à§‡ à¦šà¦¾à¦‡",                                                intent: "REGISTER_DONOR" },

    // â”€â”€â”€ UPDATE_DONATION â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    { text: "I donated blood today",                                              intent: "UPDATE_DONATION" },
    { text: "update last donation",                                               intent: "UPDATE_DONATION" },
    { text: "I gave blood",                                                       intent: "UPDATE_DONATION" },
    { text: "update my donation date",                                            intent: "UPDATE_DONATION" },
    { text: "just donated blood",                                                 intent: "UPDATE_DONATION" },
    { text: "blood donation done",                                                intent: "UPDATE_DONATION" },
    { text: "update donation record",                                             intent: "UPDATE_DONATION" },
    { text: "update phone number and last donation",                              intent: "UPDATE_DONATION" },
    { text: "change my blood donation date",                                      intent: "UPDATE_DONATION" },
    { text: "update my profile",                                                  intent: "UPDATE_DONATION" },
    { text: "edit my information",                                                intent: "UPDATE_DONATION" },
    { text: "change phone number",                                                intent: "UPDATE_DONATION" },
    // Bengali
    { text: "à¦†à¦®à¦¿ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¯à¦¼à§‡à¦›à¦¿",                                                   intent: "UPDATE_DONATION" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡à¦° à¦¤à¦¾à¦°à¦¿à¦– à¦†à¦ªà¦¡à§‡à¦Ÿ à¦•à¦°à§à¦¨",                                        intent: "UPDATE_DONATION" },
    { text: "à¦¶à§‡à¦· à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨ à¦†à¦ªà¦¡à§‡à¦Ÿ",                                                  intent: "UPDATE_DONATION" },
    { text: "à¦†à¦œ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¯à¦¼à§‡à¦›à¦¿",                                                    intent: "UPDATE_DONATION" },
    { text: "à¦—à¦¤à¦•à¦¾à¦² à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¯à¦¼à§‡à¦›à¦¿",                                                 intent: "UPDATE_DONATION" },
    { text: "à¦†à¦ªà¦¡à§‡à¦Ÿ à¦•à¦°à§à¦¨",                                                         intent: "UPDATE_DONATION" },
    { text: "à¦†à¦®à¦¾à¦° à¦«à§‹à¦¨ à¦¨à¦¾à¦®à§à¦¬à¦¾à¦° à¦à¦¬à¦‚ à¦²à¦¾à¦¸à§à¦Ÿ à¦¬à§à¦²à¦¾à¦¡ à¦¡à§‹à¦¨à§‡à¦¶à¦¨à§‡à¦° à¦¤à¦¾à¦°à¦¿à¦– à¦†à¦ªà¦¡à§‡à¦Ÿ à¦•à¦°à§‹",       intent: "UPDATE_DONATION" },
    { text: "à¦²à¦¾à¦¸à§à¦Ÿ à¦¡à§‹à¦¨à§‡à¦¶à¦¨ à¦¡à§‡à¦Ÿ à¦šà§‡à¦žà§à¦œ à¦•à¦°à§‹",                                        intent: "UPDATE_DONATION" },
    { text: "à¦ªà§à¦°à§‹à¦«à¦¾à¦‡à¦² à¦†à¦ªà¦¡à§‡à¦Ÿ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                            intent: "UPDATE_DONATION" },
    { text: "à¦†à¦®à¦¾à¦° à¦¤à¦¥à§à¦¯ à¦ªà¦°à¦¿à¦¬à¦°à§à¦¤à¦¨ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                        intent: "UPDATE_DONATION" },
    { text: "à¦«à§‹à¦¨ à¦¨à¦®à§à¦¬à¦° à¦¬à¦¦à¦²à¦¾à¦¤à§‡ à¦šà¦¾à¦‡",                                               intent: "UPDATE_DONATION" },
    { text: "à¦¨à¦¾à¦® à¦†à¦ªà¦¡à§‡à¦Ÿ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                                 intent: "UPDATE_DONATION" },
    { text: "à¦à¦²à¦¾à¦•à¦¾ à¦ªà¦°à¦¿à¦¬à¦°à§à¦¤à¦¨ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                            intent: "UPDATE_DONATION" },
    { text: "à¦°à¦•à§à¦¤à§‡à¦° à¦—à§à¦°à§à¦ª à¦†à¦ªà¦¡à§‡à¦Ÿ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                        intent: "UPDATE_DONATION" },
    { text: "à¦†à¦œà¦•à§‡ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦²à¦¾à¦®",                                                    intent: "UPDATE_DONATION" },
    { text: "à¦¸à¦«à¦²à¦­à¦¾à¦¬à§‡ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¯à¦¼à§‡à¦›à¦¿",                                                intent: "UPDATE_DONATION" },

    // â”€â”€â”€ REQUEST_BLOOD â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    { text: "request for blood",                                                  intent: "REQUEST_BLOOD" },
    { text: "submit blood request",                                               intent: "REQUEST_BLOOD" },
    { text: "post blood request",                                                 intent: "REQUEST_BLOOD" },
    { text: "blood request form",                                                 intent: "REQUEST_BLOOD" },
    { text: "create blood request",                                               intent: "REQUEST_BLOOD" },
    { text: "place a blood request",                                              intent: "REQUEST_BLOOD" },
    { text: "à¦°à¦•à§à¦¤à§‡à¦° à¦œà¦¨à§à¦¯ à¦†à¦¬à§‡à¦¦à¦¨",                                                  intent: "REQUEST_BLOOD" },
    { text: "à¦°à¦•à§à¦¤ à¦†à¦¬à§‡à¦¦à¦¨ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                                intent: "REQUEST_BLOOD" },
    { text: "à¦°à¦¿à¦•à§‹à¦¯à¦¼à§‡à¦¸à§à¦Ÿ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                                                intent: "REQUEST_BLOOD" },
    { text: "à¦¬à§à¦²à¦¾à¦¡ à¦°à¦¿à¦•à§‹à¦¯à¦¼à§‡à¦¸à§à¦Ÿ à¦«à¦°à§à¦® à¦ªà§‚à¦°à¦£ à¦•à¦°à¦¤à§‡ à¦šà¦¾à¦‡",                               intent: "REQUEST_BLOOD" },
    { text: "à¦°à¦•à§à¦¤à§‡à¦° à¦…à¦¨à§à¦°à§‹à¦§ à¦œà¦¾à¦¨à¦¾à¦¤à§‡ à¦šà¦¾à¦‡",                                           intent: "REQUEST_BLOOD" },

    // â”€â”€â”€ BLOOD_INFO â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    { text: "à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾à¦° à¦œà¦¨à§à¦¯ à¦¨à§à¦¯à§‚à¦¨à¦¤à¦® à¦¬à¦¯à¦¼à¦¸ à¦•à¦¤",                                   intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡ à¦¨à§à¦¯à§‚à¦¨à¦¤à¦® à¦“à¦œà¦¨ à¦•à¦¤ à¦¹à¦“à¦¯à¦¼à¦¾ à¦‰à¦šà¦¿à¦¤",                                 intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¤à§‡ à¦¹à¦²à§‡ à¦¬à¦¯à¦¼à¦¸ à¦•à¦¤ à¦²à¦¾à¦—à¦¬à§‡",                                        intent: "BLOOD_INFO" },
    { text: "à¦¬à§à¦²à¦¾à¦¡ à¦¡à§‹à¦¨à§‡à¦¶à¦¨à§‡à¦° à¦œà¦¨à§à¦¯ à¦¬à¦¯à¦¼à¦¸ à¦“à¦œà¦¨ à¦•à¦¤",                                    intent: "BLOOD_INFO" },
    { text: "minimum age to donate blood",                                        intent: "BLOOD_INFO" },
    { text: "minimum weight to donate blood",                                     intent: "BLOOD_INFO" },
    { text: "eligibility for blood donation",                                     intent: "BLOOD_INFO" },
    { text: "who can donate blood",                                               intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡à¦° à¦¯à§‹à¦—à§à¦¯à¦¤à¦¾ à¦•à§€",                                               intent: "BLOOD_INFO" },
    { text: "à§© à¦®à¦¾à¦¸ à¦†à¦—à§‡ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¯à¦¼à§‡à¦›à¦¿ à¦†à¦¬à¦¾à¦° à¦•à¦¿ à¦¦à¦¿à¦¤à§‡ à¦ªà¦¾à¦°à¦¬",                          intent: "BLOOD_INFO" },
    { text: "à¦•à¦¤à¦¦à¦¿à¦¨ à¦ªà¦° à¦ªà¦° à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾ à¦¯à¦¾à¦¯à¦¼",                                        intent: "BLOOD_INFO" },
    { text: "à¦†à¦¬à¦¾à¦° à¦•à¦–à¦¨ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¤à§‡ à¦ªà¦¾à¦°à¦¬",                                            intent: "BLOOD_INFO" },
    { text: "how often can I donate blood",                                       intent: "BLOOD_INFO" },
    { text: "when can I donate again",                                            intent: "BLOOD_INFO" },
    { text: "gap between blood donations",                                        intent: "BLOOD_INFO" },
    { text: "à¦Ÿà§à¦¯à¦¾à¦Ÿà§ à¦•à¦°à¦¾à¦¨à§‹à¦° à¦ªà¦° à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾ à¦¯à¦¾à¦¯à¦¼",                                   intent: "BLOOD_INFO" },
    { text: "à¦Ÿà§à¦¯à¦¾à¦Ÿà§ à¦•à¦°à¦¾à¦²à§‡ à¦•à¦¤à¦¦à¦¿à¦¨ à¦ªà¦° à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾ à¦¯à¦¾à¦¯à¦¼",                              intent: "BLOOD_INFO" },
    { text: "tattoo à¦•à¦°à¦¾à¦° à¦ªà¦° à¦°à¦•à§à¦¤ à¦¦à¦¾à¦¨",                                             intent: "BLOOD_INFO" },
    { text: "can I donate blood after tattoo",                                    intent: "BLOOD_INFO" },
    { text: "tattoo blood donation waiting period",                               intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾à¦° à¦ªà¦° à¦•à§€ à¦–à¦¾à¦¬à§‹",                                             intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡à¦° à¦ªà¦° à¦•à§‹à¦¨ à¦–à¦¾à¦¬à¦¾à¦° à¦­à¦¾à¦²à§‹",                                        intent: "BLOOD_INFO" },
    { text: "à¦¬à§à¦²à¦¾à¦¡ à¦¦à§‡à¦“à¦¯à¦¼à¦¾à¦° à¦ªà¦° à¦•à§€ à¦•à¦°à¦¬",                                             intent: "BLOOD_INFO" },
    { text: "what to eat after donating blood",                                   intent: "BLOOD_INFO" },
    { text: "after blood donation food",                                          intent: "BLOOD_INFO" },
    { text: "post donation care",                                                 intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡à¦° à¦ªà¦°à§‡ à¦¯à¦¤à§à¦¨",                                                 intent: "BLOOD_INFO" },
    { text: "à¦¥à§à¦¯à¦¾à¦²à¦¾à¦¸à§‡à¦®à¦¿à¦¯à¦¼à¦¾ à¦°à§‹à¦—à§€à¦° à¦œà¦¨à§à¦¯ à¦°à¦¿à¦®à¦¾à¦‡à¦¨à§à¦¡à¦¾à¦° à¦¸à¦¿à¦¸à§à¦Ÿà§‡à¦® à¦†à¦›à§‡",                  intent: "BLOOD_INFO" },
    { text: "à¦…à¦Ÿà§‹à¦®à§‡à¦Ÿà¦¿à¦• à¦°à¦¿à¦®à¦¾à¦‡à¦¨à§à¦¡à¦¾à¦° à¦•à¦¿ à¦†à¦›à§‡",                                        intent: "BLOOD_INFO" },
    { text: "thalassemia reminder system",                                        intent: "BLOOD_INFO" },
    { text: "automatic reminder blood donation",                                  intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤ à¦¦à¦¿à¦²à§‡ à¦•à¦¿ à¦‰à¦ªà¦•à¦¾à¦° à¦¹à¦¯à¦¼",                                              intent: "BLOOD_INFO" },
    { text: "blood donation benefits",                                            intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡à¦° à¦¸à§à¦¬à¦¿à¦§à¦¾ à¦•à¦¿",                                                 intent: "BLOOD_INFO" },
    { text: "is blood donation safe",                                             intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤ à¦¦à¦¿à¦²à§‡ à¦•à¦¿ à¦•à§à¦·à¦¤à¦¿ à¦¹à¦¯à¦¼",                                              intent: "BLOOD_INFO" },
    { text: "à¦¡à¦¾à¦¯à¦¼à¦¾à¦¬à§‡à¦Ÿà¦¿à¦¸ à¦¥à¦¾à¦•à¦²à§‡ à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾ à¦¯à¦¾à¦¬à§‡",                                   intent: "BLOOD_INFO" },
    { text: "à¦“à¦·à§à¦§ à¦–à¦¾à¦‡ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¤à§‡ à¦ªà¦¾à¦°à¦¬",                                            intent: "BLOOD_INFO" },
    { text: "sick person donate blood",                                           intent: "BLOOD_INFO" },
    { text: "diabetic blood donation",                                            intent: "BLOOD_INFO" },
    { text: "à¦¸à¦¾à¦°à§à¦¬à¦œà¦¨à§€à¦¨ à¦°à¦•à§à¦¤à¦¦à¦¾à¦¤à¦¾ à¦•à§‹à¦¨ à¦—à§à¦°à§à¦ª",                                       intent: "BLOOD_INFO" },
    { text: "universal donor blood group",                                        intent: "BLOOD_INFO" },
    { text: "O negative universal donor",                                         intent: "BLOOD_INFO" },
    { text: "à¦•à§‹à¦¨ à¦°à¦•à§à¦¤à§‡à¦° à¦—à§à¦°à§à¦ª à¦¸à¦¬à¦šà§‡à¦¯à¦¼à§‡ à¦¬à¦¿à¦°à¦²",                                      intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨ à¦•à¦¿ à¦¨à¦¿à¦°à¦¾à¦ªà¦¦",                                                   intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤ à¦¦à¦¿à¦²à§‡ à¦¶à¦°à§€à¦°à§‡ à¦•à¦¿ à¦ªà§à¦°à¦­à¦¾à¦¬ à¦ªà¦¡à¦¼à§‡",                                     intent: "BLOOD_INFO" },
    { text: "à¦‹à¦¤à§à¦¸à§à¦°à¦¾à¦¬à§‡à¦° à¦¸à¦®à¦¯à¦¼ à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾ à¦¯à¦¾à¦¬à§‡",                                    intent: "BLOOD_INFO" },
    { text: "period à¦ à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾ à¦¯à¦¾à¦¬à§‡ à¦•à¦¿",                                       intent: "BLOOD_INFO" },
    { text: "can I donate during period",                                         intent: "BLOOD_INFO" },
    { text: "à¦—à¦°à§à¦­à¦¬à¦¤à§€ à¦¹à¦²à§‡ à¦°à¦•à§à¦¤ à¦¦à§‡à¦“à¦¯à¦¼à¦¾ à¦¯à¦¾à¦¬à§‡",                                        intent: "BLOOD_INFO" },
    { text: "pregnant woman donate blood",                                        intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à§‡à¦° A+ B+ O+ AB+ à¦®à¦¾à¦¨à§‡ à¦•à¦¿",                                       intent: "BLOOD_INFO" },
    { text: "blood group meaning",                                                intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡ à¦¹à¦¿à¦®à§‹à¦—à§à¦²à§‹à¦¬à¦¿à¦¨ à¦•à¦¤ à¦¹à¦¤à§‡ à¦¹à¦¬à§‡",                                   intent: "BLOOD_INFO" },
    { text: "hemoglobin level for donation",                                      intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨à§‡à¦° à¦ªà¦° à¦•à¦¤ à¦¦à¦¿à¦¨ à¦¬à¦¿à¦¶à§à¦°à¦¾à¦®",                                        intent: "BLOOD_INFO" },
    { text: "à¦†à¦®à¦¿ à¦•à¦¿ à¦°à¦•à§à¦¤ à¦¦à¦¿à¦¤à§‡ à¦ªà¦¾à¦°à¦¬",                                              intent: "BLOOD_INFO" },
    { text: "can I donate blood",                                                 intent: "BLOOD_INFO" },
    { text: "à¦°à¦•à§à¦¤à¦¦à¦¾à¦¨ à¦¸à¦®à§à¦ªà¦°à§à¦•à§‡ à¦¤à¦¥à§à¦¯",                                               intent: "BLOOD_INFO" },

    // â”€â”€â”€ GREET â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    { text: "hello",                                                              intent: "GREET" },
    { text: "hi",                                                                 intent: "GREET" },
    { text: "hey",                                                                intent: "GREET" },
    { text: "good morning",                                                       intent: "GREET" },
    { text: "good evening",                                                       intent: "GREET" },
    { text: "good afternoon",                                                     intent: "GREET" },
    { text: "what can you do",                                                    intent: "GREET" },
    { text: "who are you",                                                        intent: "GREET" },
    { text: "what is this bot",                                                   intent: "GREET" },
    { text: "start",                                                              intent: "GREET" },
    { text: "à¦¹à§à¦¯à¦¾à¦²à§‹",                                                              intent: "GREET" },
    { text: "à¦¹à¦¾à¦‡",                                                                 intent: "GREET" },
    { text: "à¦†à¦¸à§à¦¸à¦¾à¦²à¦¾à¦®à§ à¦†à¦²à¦¾à¦‡à¦•à§à¦®",                                                  intent: "GREET" },
    { text: "à¦¸à¦¾à¦²à¦¾à¦®",                                                               intent: "GREET" },
    { text: "à¦¶à§à¦­ à¦¸à¦•à¦¾à¦²",                                                           intent: "GREET" },
    { text: "à¦¶à§à¦­ à¦¬à¦¿à¦•à§‡à¦²",                                                          intent: "GREET" },
    { text: "à¦¶à§à¦­ à¦°à¦¾à¦¤à§à¦°à¦¿",                                                          intent: "GREET" },
    { text: "à¦•à§‡à¦®à¦¨ à¦†à¦›à§‹",                                                           intent: "GREET" },
    { text: "à¦•à§‡à¦®à¦¨ à¦†à¦›à§‡à¦¨",                                                          intent: "GREET" },
    { text: "à¦­à¦¾à¦²à§‹ à¦†à¦›à§‹",                                                           intent: "GREET" },
    { text: "à¦¤à§à¦®à¦¿ à¦•à§‡",                                                             intent: "GREET" },
    { text: "à¦¤à§à¦®à¦¿ à¦•à¦¿ à¦•à¦°à¦¤à§‡ à¦ªà¦¾à¦°à§‹",                                                  intent: "GREET" },
    { text: "à¦à¦‡ à¦¬à¦Ÿ à¦•à¦¿ à¦•à¦°à§‡",                                                       intent: "GREET" },

    // â”€â”€â”€ HELP â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    { text: "help",                                                               intent: "HELP" },
    { text: "how does this work",                                                 intent: "HELP" },
    { text: "menu",                                                               intent: "HELP" },
    { text: "show menu",                                                          intent: "HELP" },
    { text: "options",                                                            intent: "HELP" },
    { text: "what are the commands",                                              intent: "HELP" },
    { text: "how to use",                                                         intent: "HELP" },
    { text: "guide me",                                                           intent: "HELP" },
    { text: "à¦¸à¦¾à¦¹à¦¾à¦¯à§à¦¯",                                                             intent: "HELP" },
    { text: "à¦¸à¦¾à¦¹à¦¾à¦¯à§à¦¯ à¦•à¦°à§à¦¨",                                                        intent: "HELP" },
    { text: "à¦®à§‡à¦¨à§",                                                                intent: "HELP" },
    { text: "à¦•à¦¿ à¦•à¦°à¦¬",                                                             intent: "HELP" },
    { text: "à¦•à¦¿à¦­à¦¾à¦¬à§‡ à¦•à¦¾à¦œ à¦•à¦°à§‡",                                                     intent: "HELP" },
    { text: "à¦•à¦¿à¦­à¦¾à¦¬à§‡ à¦¬à§à¦¯à¦¬à¦¹à¦¾à¦° à¦•à¦°à¦¬",                                                  intent: "HELP" },
    { text: "à¦•à¦¿ à¦•à¦¿ à¦•à¦°à¦¾ à¦¯à¦¾à¦¯à¦¼",                                                      intent: "HELP" },
    { text: "à¦¬à§à¦à¦¤à§‡ à¦ªà¦¾à¦°à¦›à¦¿ à¦¨à¦¾",                                                     intent: "HELP" },
    { text: "à¦¸à¦¾à¦¹à¦¾à¦¯à§à¦¯ à¦²à¦¾à¦—à¦¬à§‡",                                                       intent: "HELP" },
    { text: "à¦—à¦¾à¦‡à¦¡ à¦•à¦°à§à¦¨",                                                           intent: "HELP" },

    // â”€â”€â”€ THANK_YOU â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    { text: "thank you",                                                          intent: "THANK_YOU" },
    { text: "thanks",                                                             intent: "THANK_YOU" },
    { text: "thanks a lot",                                                       intent: "THANK_YOU" },
    { text: "thank you so much",                                                  intent: "THANK_YOU" },
    { text: "great thanks",                                                       intent: "THANK_YOU" },
    { text: "helpful thanks",                                                     intent: "THANK_YOU" },
    { text: "ok thank you",                                                       intent: "THANK_YOU" },
    { text: "okay thanks",                                                        intent: "THANK_YOU" },
    { text: "got it thanks",                                                      intent: "THANK_YOU" },
    { text: "bye",                                                                intent: "THANK_YOU" },
    { text: "goodbye",                                                            intent: "THANK_YOU" },
    { text: "see you",                                                            intent: "THANK_YOU" },
    { text: "à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦",                                                             intent: "THANK_YOU" },
    { text: "à¦…à¦¨à§‡à¦• à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦",                                                        intent: "THANK_YOU" },
    { text: "à¦¶à§à¦•à¦°à¦¿à¦¯à¦¼à¦¾",                                                             intent: "THANK_YOU" },
    { text: "à¦†à¦ªà¦¨à¦¾à¦•à§‡ à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦",                                                     intent: "THANK_YOU" },
    { text: "à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦ à¦†à¦ªà¦¨à¦¾à¦•à§‡",                                                     intent: "THANK_YOU" },
    { text: "à¦–à§à¦¬ à¦¸à¦¾à¦¹à¦¾à¦¯à§à¦¯ à¦¹à¦¯à¦¼à§‡à¦›à§‡ à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦",                                          intent: "THANK_YOU" },
    { text: "à¦¬à§à¦à¦¤à§‡ à¦ªà§‡à¦°à§‡à¦›à¦¿ à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦",                                               intent: "THANK_YOU" },
    { text: "à¦ à¦¿à¦• à¦†à¦›à§‡ à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦",                                                    intent: "THANK_YOU" },
    { text: "à¦†à¦²à§à¦²à¦¾à¦¹ à¦¹à¦¾à¦«à§‡à¦œ",                                                        intent: "THANK_YOU" },
    { text: "à¦¬à¦¾à¦‡",                                                                 intent: "THANK_YOU" },
    { text: "à¦†à¦¬à¦¾à¦° à¦•à¦¥à¦¾ à¦¹à¦¬à§‡",                                                        intent: "THANK_YOU" },
    { text: "à¦•à¦¾à¦œ à¦¹à¦¯à¦¼à§‡à¦›à§‡ à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦",                                                   intent: "THANK_YOU" },
];

export const INTENTS: Intent[] = [
    "FIND_BLOOD",
    "REGISTER_DONOR",
    "UPDATE_DONATION",
    "REQUEST_BLOOD",
    "BLOOD_INFO",
    "GREET",
    "HELP",
    "THANK_YOU",
    "UNKNOWN",
];
